# Generated by Django 5.0.3 on 2024-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_global_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('Proffesional', 'Proffesional')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
